apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: apr23-quarkus-test-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: apr23-quarkus-test-1
  name: apr23-quarkus-test-1
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: apr23-quarkus-test-1
